version: "3.4"

services:
  php:
    image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:php-${GITHUB_SHA}
    build:
      cache_from:
        - ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:php-latest

  api:
    image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:api-${GITHUB_SHA}
    build:
      cache_from:
        - ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:api-latest

  client:
    image: ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:client-${GITHUB_SHA}
    build:
      target: client-prod
      args:
        API_ENDPOINT: ${API_ENDPOINT}
      cache_from:
        - ${GAR_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:client-latest
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
