apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    project:  cataclop
    env: {{ .Values.kubernetesEnv }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        service: client
        project: cataclop
        env: {{ .Values.kubernetesEnv }}
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}-client
          image: "{{ .Values.containerImageRepository }}:{{ .Values.client.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 15
          resources:
            requests:
              cpu: "25m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
