apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    project: cataclop
    env: {{ .Values.kubernetesEnv }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: client
  selector:
    service: client
